"""
Isaac Lab ArticulationCfg for the wheelchair robot.

This config references wheelchair_unified.usd generated by:
    generate_wheelchair_unified.py

Usage in Isaac Lab:
    from wheelchair_description.urdf.wheelchair_isaac_lab_cfg import WHEELCHAIR_CFG
"""

import os

from isaaclab.actuators import ImplicitActuatorCfg
from isaaclab.assets import ArticulationCfg
from isaaclab.sim import UsdFileCfg

# Path to the unified USD (same directory as this file)
_USD_DIR = os.path.dirname(os.path.abspath(__file__))
_USD_PATH = os.path.join(_USD_DIR, "wheelchair_unified.usd")

WHEELCHAIR_CFG = ArticulationCfg(
    spawn=UsdFileCfg(usd_path=_USD_PATH),
    init_state=ArticulationCfg.InitialStateCfg(
        pos=(0.0, 0.0, 0.2),  # base_link is 0.2m above ground in URDF
    ),
    actuators={
        "wheels": ImplicitActuatorCfg(
            joint_names_expr=["leftwheel", "rightwheel"],
            velocity_limit=1.6,  # rad/s (~0.25 m/s at r=0.1524m)
            effort_limit=50.0,
            stiffness=0.0,  # velocity control
            damping=200.0,
        ),
    },
)
