from setuptools import setup, find_packages

package_name = 'wheelchair_localization'

setup(
    name=package_name,
    version='0.0.0',
    packages=find_packages(exclude=['test']),
    data_files=[
        ('share/ament_index/resource_index/packages',
            ['resource/' + package_name]),
        ('share/' + package_name, ['package.xml']),
        ('share/' + package_name + '/config', [
            'config/laser_filter.yaml',
            'config/laser_filter_robust.yaml',
            'config/ekf.yaml',
            'config/ekf_global.yaml',
            'config/amcl_fusion.yaml',
            'config/slam_toolbox_motion_compensated.yaml',
            'config/slam_toolbox_fused.yaml',
            'config/slam_toolbox_fused_robust.yaml',
            'config/slam_toolbox_fused_v2.yaml',
            'config/slam_toolbox_fused_v3.yaml',
            'config/slam_toolbox_fused_v4.yaml',
            'config/slam_toolbox_fused_v5.yaml',
            'config/slam_toolbox_fused_v6.yaml',
            'config/slam_toolbox_fused_v7.yaml',
            'config/slam_toolbox_fused_v8.yaml',
            'config/slam_toolbox_fused_v9.yaml',
            'config/slam_toolbox_fused_v10.yaml',
            'config/slam_toolbox_fused_v11.yaml',
            'config/slam_toolbox_fused_v12.yaml',
            'config/slam_toolbox_fused_v13.yaml',
            'config/slam_toolbox_fused_v14.yaml',
            'config/slam_toolbox_fused_v15.yaml',
            'config/slam_toolbox_fused_v16.yaml',
            'config/slam_toolbox_fused_v17.yaml',
            'config/slam_toolbox_fused_v18.yaml',
            'config/slam_toolbox_fused_v19.yaml',
            'config/slam_toolbox_fused_v20.yaml',
            'config/slam_toolbox_fused_v21.yaml',
            'config/slam_toolbox_motion_compensated_v2.yaml',
            'config/laser_filter_hospital.yaml',
            'config/slam_toolbox_hospital_lidar.yaml',
            'config/slam_toolbox_hospital_lidar_v2.yaml',
            'config/slam_toolbox_hospital_fused.yaml',
            'config/slam_toolbox_hospital_lidar_v3.yaml',
            'config/slam_toolbox_hospital_fused_v2.yaml',
        ]),
        ('share/' + package_name + '/launch', ['launch/sensor_fusion.launch.py']),
    ],
    install_requires=['setuptools', 'numpy'],
    zip_safe=True,
    maintainer='sidd',
    maintainer_email='s24035@students.iitmandi.ac.in',
    description='Wheelchair localization - EKF, AMCL, laser filters',
    license='MIT',
    tests_require=['pytest'],
    entry_points={
        'console_scripts': [
            'scan_depth_fusion_node = wheelchair_localization.scan_depth_fusion_node:main',
            'multi_camera_scan_fusion = wheelchair_localization.multi_camera_scan_fusion:main',
            'multi_camera_scan_fusion_sota = wheelchair_localization.multi_camera_scan_fusion_sota:main',
            'multi_camera_scan_fusion_simple = wheelchair_localization.multi_camera_scan_fusion_simple:main',
            'scan_fusion_optimized = wheelchair_localization.scan_fusion_optimized:main',
            'scan_fusion_realtime = wheelchair_localization.scan_fusion_realtime:main',
            'scan_fusion_ultra = wheelchair_localization.scan_fusion_ultra:main',
            'scan_fusion_ultimate = wheelchair_localization.scan_fusion_ultimate:main',
            'scan_fusion_lite = wheelchair_localization.scan_fusion_lite:main',
            'robust_scan_fusion = wheelchair_localization.robust_scan_fusion:main',
            'scan_fusion_v2 = wheelchair_localization.scan_fusion_v2:main',
            'camera_lidar_fusion = wheelchair_localization.camera_lidar_fusion:main',
            'scan_fusion_v3 = wheelchair_localization.scan_fusion_v3:main',
            'scan_fusion_v4 = wheelchair_localization.scan_fusion_v4:main',
            'scan_fusion_v5 = wheelchair_localization.scan_fusion_v5:main',
            'scan_fusion_v6 = wheelchair_localization.scan_fusion_v6:main',
            'scan_fusion_v7 = wheelchair_localization.scan_fusion_v7:main',
            'scan_fusion_v8 = wheelchair_localization.scan_fusion_v8:main',
            'scan_fusion_v9 = wheelchair_localization.scan_fusion_v9:main',
            'scan_fusion_v10 = wheelchair_localization.scan_fusion_v10:main',
            'odom_velocity_corrector = wheelchair_localization.odom_velocity_corrector:main',
            'scan_lidar = wheelchair_localization.scan_lidar:main',
            'scan_footprint_mask = wheelchair_localization.scan_footprint_mask:main',
        ],
    },
)
